//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPublicationEntities : DbContext
    {
        public DbPublicationEntities()
            : base("name=DbPublicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<ConferenceArticle> ConferenceArticle { get; set; }
        public virtual DbSet<JournalArticle> JournalArticle { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<QualificationThesis> QualificationThesis { get; set; }
        public virtual DbSet<TechnicalReport> TechnicalReport { get; set; }
    }
}
