//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationThesis
    {
        public int PublicationId { get; set; }
        public string School { get; set; }
        public string ThesisType { get; set; }
        public string Address { get; set; }
    
        public virtual Publication Publication { get; set; }
    }
}
